import type { Metadata } from "next";
import type { Viewport } from 'next';
import localFont from "next/font/local";
import "./globals.css";

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export const viewport: Viewport = {
  initialScale: 1,
  width: 'device-width',
  maximumScale: 1,
  userScalable: false
}

import Link from 'next/link';

const items = [
  { id: 1, title: "Главная", rout: "/" },
  { id: 2, title: "Первый семестр", rout: "/1st-sem" },
  { id: 3, title: "Второй семестр", rout: "-" },
  { id: 4, title: "Услуги", rout: "/services" },
  { id: 5, title: "Авторизация", rout: "-" }
]

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <head>
        <link href="https://fonts.googleapis.com/css2?family=Caveat:wght@400..700&display=swap" rel="stylesheet" />
      </head>
      <body className={`${geistSans.variable} ${geistMono.variable} antialiased`}>
        <header className="bg-[#0a493f] text-white p-3 text-xl flex flex-col gap-y-2">
          <div className = 'flex justify-between border-b-white border-b-2 pb-2'>
            <div className="flex flex-col justify-center">
              <img src="https://cdn-icons-png.freepik.com/512/16109/16109898.png?ga=GA1.1.1800914785.1694778387" alt="logo" className="w-16 aspect-square" />
              <div>Logo</div>
            </div>
            <div className="flex flex-col justify-center">
              ЭФБО-01-23 <br />
              Долгова С. С.
            </div>
          </div>
          <div className='menu flex justify-between flex-wrap gap-y-2 text-2xl'>
            {items.map((item) => (
                <Link className='button border-x-2 border-white px-2 py-1 hover:shadow-md hover:italic' key={item.id} href={item.rout}> | {item.title} |</Link>
            ))}
          </div>
        </header>
        <main>
          {children}
        </main>
        <footer className="bg-gray-300 p-5">
            <div className="flex justify-center">&copy; Долгова Софья Сергеевна, 2024</div>
            <div className="flex gap-x-2 justify-center">
              <a href="https://github.com/sofyads/frontick">
                <img src="https://as2.ftcdn.net/v2/jpg/02/50/30/59/1000_F_250305943_sDC6la1N1fDl3bLgfLxOkQwItIodsdMb.jpg" alt="github" className="w-10 h-10 rounded-full" />
              </a>
              <a href="https://t.me/sofyads">
                <img src="https://avatars.mds.yandex.net/get-socsnippets/13272848/2a000001930216578446b447621f37cd95b3/square_166" alt="telegram" className="w-10 h-10 rounded-full" />
              </a>
            </div>
        </footer>
        
      </body>
    </html>
  );
}
